### ISSUE TITLE
Redis db error 

### ISSUE THREAD

**Issue by jakubmat2001** [aneagoie/smart-brain-boost-api-dockerized#19]
Hey, after executing commands from the readme file I have encountered an error supposedly coming from Redis. I've run the npm install followed by docker-compose up --build command and received the following error in the terminal (check the attached file). I've done
![error](https://github.com/aneagoie/smart-brain-boost-api-dockerized/assets/87088367/c92009ae-0453-41dd-81aa-61e07369c8b8)
 docker-compose down and any other commands suggested in readme, but with no help.

**Comment by elunaj** [comment]
@jakubmat2001 I'm having the same issue. Did you find a solution?
